services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:database

  database:
    container_name: database
    image: surrealdb/surrealdb:v1.4.2-dev
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --allow-guests
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --log
      - $DB_LOG_LEVEL
      - file:/db/surreal.db
    volumes:
      - ./db:/db

volumes:
  db:
    name: db
